# Generated by Django 4.0.5 on 2022-06-30 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_rename_emai_contributor_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='rationg',
            new_name='rating',
        ),
    ]
